config/routes.rb
Rails.application.routes.draw do
  resources :musics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "musics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/music.rb
class Music < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: %i[ show edit update destroy ]

  # GET /musics or /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1 or /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics or /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to music_url(@music), notice: "Music was successfully created." }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1 or /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to music_url(@music), notice: "Music was successfully updated." }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1 or /musics/1.json
  def destroy
    @music.destroy!

    respond_to do |format|
      format.html { redirect_to musics_url, notice: "Music was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def music_params
      params.require(:music).permit(:image, :name, :artist, :description_music, :biography_artist, :link, :spotify_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>

    <footer>
      <div class="footer">
      <p>©2024-All rights reserved</p>
      <p>Made with: Ruby On Rails, Visual Studio Code, Bootstrap, Midjourney</p>
      <p>BEAUNE Adèle, GELIS Justine </p>
      </div>
    </footer>
  </body>
</html>

app/views/musics/_form.html.erb
<%= form_with(model: music) do |form| %>
  <% if music.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
        <% music.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block", class: 'form_label' %>
    <%= form.text_area :image, class: 'form_text_area' %>
  </div>

  <div>
    <%= form.label :name, style: "display: block", class: 'form_label' %>
    <%= form.text_field :name, class: 'form_text_area' %>
  </div>

  <div>
    <%= form.label :artist, style: "display: block", class: 'form_label' %>
    <%= form.text_field :artist, class: 'form_text_area' %>
  </div>

  <div>
    <%= form.label :description_music, style: "display: block", class: 'form_label' %>
    <%= form.text_area :description_music, class: 'form_text_area' %>
  </div>

  <div>
    <%= form.label :biography_artist, style: "display: block", class: 'form_label' %>
    <%= form.text_area :biography_artist, class: 'form_text_area' %>
  </div>

  <div>
    <%= form.label :spotify_id, style: "display: block", class: 'form_label' %>
    <%= form.text_area :spotify_id, class: 'form_text_area' %>
  </div>

  <div>
    <%= form.submit 'Submit', class: 'form_submit' %>
  </div>
<% end %>

app/views/musics/_music.html.erb
<div id="<%= dom_id music %>">
  <p>
    <strong>Image:</strong>
    <%= music.image %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= music.name %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= music.artist %>
  </p>

  <p>
    <strong>Description music:</strong>
    <%= music.description_music %>
  </p>

  <p>
    <strong>Biography artist:</strong>
    <%= music.biography_artist %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= music.link %>
  </p>

  <p>
    <strong>Spotify:</strong>
    <%= music.spotify_id %>
  </p>

</div>

app/views/musics/edit.html.erb
<section class="edit">
  <div class="edit_center">
    <h1>Editing music</h1>
    <%= render "form", music: @music %>
    <br>
    <div class="link">
      <%= link_to "Show this music", @music, class: 'link_back_show_music' %>
      <%= link_to "Retour à l'accueil", musics_path, class: 'link_back_show_music'%>
    </div>
  </div>
  
</section>

app/views/musics/index.html.erb
<%# Partie header %>
<section class="header ">
  <div class="container">
    <div class="row">
        <div class="col-6">
            <h1>Spotart</h1>
            <p class="description">Vous voulez connaître l’histoire des musiques et des artistes ? Tant mieux, vous êtes au bon endroit !</p>
        </div>
        <div class="nouveaux_header col-6">
          <%= image_tag("nouveaux_artistes.png", alt: "image qui représente des nouveaux artistes", class: "nouveaux_artistes") %>
          <p>LES NOUVEAUTES</p>
        </div>
    </div>
      <p class="decouvrir">Découvrez leur histoire </p>
      <a href="#musics"><%= image_tag("fleche_bas.png", class: "fleche_bas") %></a>
  </div>
</section>


<%# Partie musique %>
<section class="musics" id="musics">
  <div class="container">
    <%# affiche la boite d'une musique %>
    <div class="row">
      <% @musics.each do |music| %>
        <div class="ligne_musics col-md-4">
            <div class="music">
                <div class="music_img">
                    <img src=" <%= music.image %> " alt="image de la musique">
                </div>
                <div class="music_description">
                   <p> <%= music.name %> </p>
                   <p> <%= music.artist %> </p>
                    <%= link_to 'Découvrir l’histoire', music, class: 'music_lien' %>
                </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container">
    <div class="music_div_new row">
      <%= link_to "New music", new_music_path, class: 'music_new col-md-2' %>
    </div>
  </div>
</section>

app/views/musics/new.html.erb
<section class="new">
  <div class="new_center">
    <h1>Nouvelle musique</h1>
    <%= render "form", music: @music %>
    <br>
    <div>
    <%= link_to "Retour à l'accueil", musics_path, class: 'link_back_show_music'%>
    </div>
  </div>
  
</section>

app/views/musics/show.html.erb
<section id="musics" class="show"> 
    <div class="div_flex">
        <img src="<%= @music.image%>" alt="cover du son" class='img_show'>
        <div class="div_p">
            <p> <%= @music.artist %> </p>
            <p> <%= @music.name %> </p>
            <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/<%= @music.spotify_id %>?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
        </div>
    </div>
    <p class="p_bio_music"><span>Biographie de l'artiste :</span> <%= @music.biography_artist %> </p>
    <p class="p_bio_music"><span>Histoire de la musique :</span> <%= @music.description_music %> </p>
    <div class='div_lien_show'>
        <%= link_to "Editer de la musique", edit_music_path, class: 'show_edit' %>
        <%# <%= button_to "Supprimer la musique", @game, method: :delete, class: 'delete_music' %> 
    </div>
    <%= link_to "Retour à l'accueil", musics_path, class: 'link_back_show_music back_show'%>
    

</section>